name: make_hats_env
channels:
  - anaconda
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.13=py313h8060acc_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - astropy-base=7.1.0=py313h607aa3e_0
  - astropy-iers-data=0.2025.6.9.0.39.3=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.9.0=hbfa7f16_15
  - aws-c-cal=0.9.2=h5e3027f_0
  - aws-c-common=0.12.3=hb9d3cd8_0
  - aws-c-compression=0.3.1=hafb2847_5
  - aws-c-event-stream=0.5.4=h76f0014_12
  - aws-c-http=0.10.2=h015de20_2
  - aws-c-io=0.20.1=hdfce8c9_0
  - aws-c-mqtt=0.13.1=h1e5e6c0_3
  - aws-c-s3=0.8.1=h5e174a9_3
  - aws-c-sdkutils=0.2.4=hafb2847_0
  - aws-checksums=0.2.7=hafb2847_1
  - aws-crt-cpp=0.32.8=ha15c642_6
  - aws-sdk-cpp=1.11.510=h4607db7_10
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - blosc=1.21.6=he440d0b_1
  - bokeh=3.7.3=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.1.0=py313h46c70d0_3
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.18.0=h3122c55_0
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cdshealpix=0.7.1=py313h920b4c0_2
  - certifi=2025.6.15=pyhd8ed1ab_0
  - cffi=1.17.1=py313hfab6e84_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py313h33d0bda_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.0.1=py313h536fd9c_0
  - dask=2025.3.0=pyhd8ed1ab_0
  - dask-core=2025.3.0=pyhd8ed1ab_0
  - dask-jobqueue=0.9.0=pyhd8ed1ab_0
  - debugpy=1.8.14=py313h46c70d0_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - distributed=2025.3.0=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - fonttools=4.58.4=py313h8060acc_0
  - freetype=2.13.3=ha770c72_1
  - frozenlist=1.6.0=py313h61b7b33_0
  - fsspec=2025.5.1=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.14.0=nompi_py313hfaf8fd4_100
  - hats=0.6=pyhd8ed1ab_0
  - hats-import=0.6.0=pyhd8ed1ab_0
  - hdf5=1.14.6=nompi_h2d575fe_101
  - hpack=4.1.0=pyhd8ed1ab_0
  - hpgeom=1.4.0=py313ha014f3b_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.3.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jproperties=2.1.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py313h33d0bda_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h1423503_5
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libaec=1.1.4=h3f801dc_0
  - libarrow=20.0.0=h314c690_7_cpu
  - libarrow-acero=20.0.0=hcb10f89_7_cpu
  - libarrow-dataset=20.0.0=hcb10f89_7_cpu
  - libarrow-substrait=20.0.0=h1bed206_7_cpu
  - libblas=3.9.0=32_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=32_he106b2a_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libgomp=15.1.0=h767d61c_2
  - libgoogle-cloud=2.36.0=hc4361e1_1
  - libgoogle-cloud-storage=2.36.0=h0121fbd_1
  - libgrpc=1.71.0=h8e591d7_1
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libopentelemetry-cpp=1.21.0=hd1b1c89_0
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_0
  - libparquet=20.0.0=h081d1f1_7_cpu
  - libpng=1.6.49=h943b412_0
  - libprotobuf=5.29.3=h501fc15_1
  - libre2-11=2024.07.02=hba17884_3
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.1=h6cd9bfd_6
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.0=hf01ce69_5
  - libutf8proc=2.10.0=h202a827_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.44.0=py313h1b76d92_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lsdb=0.6.0=pyhd8ed1ab_0
  - lsst-sphgeom=28.2025.200=py313ha87cce1_0
  - lz4=4.4.4=py313h8756d67_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.2=py313h8060acc_1
  - matplotlib-base=3.10.3=py313h129903b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mocpy=0.18.0=py313h920b4c0_0
  - msgpack-python=1.1.1=py313h33d0bda_0
  - multidict=6.5.0=py313h8060acc_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=1.44.0=pyhe01879c_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nested-pandas=0.4.5=pyhd8ed1ab_0
  - networkx=3.5=pyhe01879c_0
  - nlohmann_json=3.11.2=h6a678d5_0
  - nomkl=1.0=h5ca1d4c_0
  - numba=0.61.2=py313h50b8c88_1
  - numexpr=2.10.2=py313h5f97788_100
  - numpy=2.2.6=py313h17eae1a_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.0=h7b32b05_1
  - orc=2.1.2=h17f744e_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.0=py313ha87cce1_0
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.2.1=py313h8db990d_0
  - pip=25.1.1=pyh145f28c_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - propcache=0.3.1=py313h8060acc_0
  - psutil=7.0.0=py313h536fd9c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pyarrow=20.0.0=py313h78bf25f_0
  - pyarrow-core=20.0.0=py313he5f92c8_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py313h4b2b08d_0
  - pyerfa=2.0.1.5=py313ha014f3b_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytables=3.10.2=py313h49b9dc6_5
  - python=3.13.5=hec9711d_102_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=7_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py313h8060acc_2
  - pyzmq=27.0.0=py313h8e95178_0
  - qhull=2020.2=h434a139_5
  - re2=2024.07.02=h9925aae_3
  - readline=8.2=h8c095d6_2
  - regions=0.10=py313ha014f3b_1
  - requests=2.32.4=pyhd8ed1ab_0
  - s2n=1.5.21=h7ab7c64_0
  - scipy=1.15.2=py313h86fcf2b_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tables-io=1.0.0=pyhb29723e_1
  - tblib=3.1.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.1=py313h536fd9c_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.14.0=h32cad80_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - universal_pathlib=0.2.6=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wrapt=1.17.2=py313h536fd9c_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.20.1=py313h8060acc_0
  - zeromq=4.3.5=h3b0a872_7
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.4=h7955e40_0
  - zstandard=0.23.0=py313h536fd9c_2
  - zstd=1.5.7=hb8e6e7a_2
